name: Rust

on:
  push:
    paths: 
    - "**.rs"
    - "Cargo.toml"
    - "rust-toolchain.toml"
    - ".github/workflows/rust.yml"
  pull_request:
  workflow_call:

env:
    CARGO_TERM_COLOR: always

jobs:

  skip_check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.1
        with:
          concurrent_skipping: 'same_content_newer'

  test:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        channel:
          - "nightly"
        test_flags: 
          - ""
          - "no_diagnostic"
          - "no_try"
          - "no_diagnostic:no_try"
        include:
          - channel: "stable"
            test_flags: ""

    env:
      PROC_MACRO2_DIAGNOSTIC_TEST: ${{ matrix.test_flags }}
  
    steps:
    - uses: actions/checkout@v7.0.0
    - name: Run tests
      run: cargo +${{ matrix.channel }} test

  lint:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        channel:
          - "nightly"
        test_flags: 
          - ""
          - "no_diagnostic"
          - "no_try"
          - "no_diagnostic:no_try"
        include:
          - channel: "stable"
            test_flags: ""

    env:
      PROC_MACRO2_DIAGNOSTIC_TEST: ${{ matrix.test_flags }}

    steps:
    - uses: actions/checkout@v7.0.0
    - run: rustup install
    - name: clippy
      run: cargo +${{ matrix.channel }} clippy -- --deny warnings

  fmt:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7.0.0
    - name: fmt
      run: cargo fmt --check

  msrv:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    env:
      RUSTC_BOOTSTRAP: 1

    steps:
    - uses: actions/checkout@v7.0.0
    - name: install cargo-msrv
      uses: taiki-e/install-action@v2.82.2
      with:
        tool: cargo-msrv
    - name: check MSRV
      run: cargo msrv verify
