name: Rust

on:
  push:
    paths: 
    - "**.rs"
    - "Cargo.toml"
    - "rust-toolchain.toml"
    - ".github/workflows/rust.yml"
  pull_request:
  workflow_call:

env:
    CARGO_TERM_COLOR: always

jobs:

  skip_check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5.3.1
        with:
          concurrent_skipping: 'same_content_newer'

  test:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        channel:
          - "nightly"
        allow-features:
          - "[\"proc_macro_span\",\"try_trait_v2\",\"never_type\",\"try_trait_v2_residual\",\"iterator_try_collect\"]"
          - "[\"proc_macro_span\",\"proc_macro_diagnostic\"]"
          - "" # all
        include:
          - channel: "stable"
            allow-features: ""
  
    steps:
    - uses: actions/checkout@v7.0.0
    - name: set allow-features
      if: ${{ matrix.allow-features }}
      run: echo 'unstable.allow-features = ${{ matrix.allow-features }}' > .cargo/config.toml
    - name: Run tests
      run: cargo +${{ matrix.channel }} test

  lint:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        channel:
          - "nightly"
        allow-features:
          - "[\"proc_macro_span\",\"try_trait_v2\",\"never_type\",\"try_trait_v2_residual\",\"iterator_try_collect\"]"
          - "[\"proc_macro_span\",\"proc_macro_diagnostic\"]"
          - "" # all
        include:
          - channel: "stable"
            allow-features: ""

    steps:
    - uses: actions/checkout@v7.0.0
    - run: rustup install
    - name: set allow-features
      if: ${{ matrix.allow-features }}
      run: echo 'unstable.allow-features = ${{ matrix.allow-features }}' > .cargo/config.toml
    - name: clippy
      run: cargo +${{ matrix.channel }} clippy -- --deny warnings

  fmt:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7.0.0
    - name: fmt
      run: cargo fmt --check

  msrv:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    env:
      RUSTC_BOOTSTRAP: 1

    steps:
    - uses: actions/checkout@v7.0.0
    - name: install cargo-msrv
      uses: taiki-e/install-action@v2.82.10
      with:
        tool: cargo-msrv
    - name: check MSRV
      run: cargo msrv verify
